Attachments data
OS2Forms/os2forms_rest_api pull request #3
Opened 2023-02-27 19:39 UTC by rimi-itk

Adds attachment data to `GET` respoonses:

```json
{
  …
  "data": {
    …
    "attachments": {
      "attachment_pdf": {
        "name": "Attachment (pdf)",
        "type": "pdf",
        "url": "http://os2forms.example.com/da/webform/os2forms/submissions/42/attachment/pdf/pdf.pdf"
      },
      …
    }
  }
}
```

2023-02-28 08:06 UTC, jekuaitk approved these changes

2023-03-01 12:11 UTC, stanbellcom requested changes

2023-03-01 12:11 UTC, stankut commented on composer.json
> +            }
I suggest to keep patch path as a local path, not github URL. That helps to avoid problem if this is changed or is not available anymore for any reasons

2023-03-01 13:22 UTC, stanbellcom approved these changes

2023-03-01 14:32 UTC, merged